
permalink:           pretty
# Setup
title:               'Machine Learining'
homepage_title:      Home
url:                 https://iknyazeva.github.io/ML2020/
baseurl:             '/ML2020'

src:                 "."
default_theme:       "rust"

# For Maths
markdown:            kramdown
 
prologues:
  - path: about.md
  - path: tools.md
chapters:
 - path: week01/01.md
   sections:
     - path: tools.md
     - path: week01/01-2.md
